@startuml
"Streaming Service" -> "Eventhub SM/TelemetryDataChanged": Streaming data
"Eventhub SM/TelemetryDataChanged" -> "AAS Convertor Function": triggers
"AAS Convertor Function" -> "Eventhub AAS/TelemetryDataChanged": Sending AAS format
@enduml
