@startuml
"Streaming Service" -> "Eventhub Factory/TelemetryDataChanged": Streaming data
"Eventhub Factory/TelemetryDataChanged" -> "AAS Convertor Function": triggers
"AAS Convertor Function" -> "Eventhub AAS/TelemetryDataChanged": Sending AAS format
@enduml
