@startuml
"Factory Pipeline" -> "Blob Storage": Save factory model to blob storage
"Factory Pipeline" -> "Eventhub Namespace": Send message with factory blob storage path
"Eventhub Namespace" -> "Raw to AAS AZ Function": Triggers Raw to AAS function
"Raw to AAS AZ Function" -> "Blob Storage": Get factory model from blob path
"Blob Storage" --> "Raw to AAS AZ Function": Returns the factory model data
"Raw to AAS AZ Function" -> "Raw to AAS AZ Function": Convert raw factory model data to AAS
"Raw to AAS AZ Function" -> "Blob Storage": Save AAS to blob storage
"Raw to AAS AZ Function" -> "Eventhub Namespace": New event to trigger AAS to ADT
@enduml